Fix/same nonce replacement txs
ConsenSys-archive/ganache pull request #1237
Opened 2021-09-22 20:31 UTC by MicaiahReid

Prevents a transaction that replace a previously queued transaction from being re-added to the transaction pool and thus run twice.

Previously when a transaction was sent we checked:
- do we have executable transactions in the transaction pool from the same origin?
- does this new transaction have the same nonce as one of those?
- if so, is this new transaction's gas price better?
- if so, replace the previous transaction with this new one.

We now perform all of those same checks against the future-nonce transactions (transactions whose nonce is higher than the sender account's nonce) in the transaction pool, not just the executable transactions.

2021-09-22 20:37 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/transaction-pool.ts
> +      for (let i = 0; i < length; i++) {
This is mostly the same as the for loop [above](https://github.com/trufflesuite/ganache/pull/1237/files#diff-ca13abb534f8ddc94c9f9ae1309a903ad18f3f06f07b94653412d29f006178b2R151-R187), the differences being:
- above we set `transactionPlacement` to `TriageOptions.ReplacesExecutableTransaction`; here we set it to `TriageOptions.ReplacesFutureTransaction`
- above we need to track the `highestNonce`; here we do not.

I couldn't think of a great way to DRY this up. Every time I tried I only made it uglier. But I'm definitely open to suggestions.

2021-09-24 16:00 UTC, davidmurdoch requested changes

2021-09-24 16:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/transaction-pool.ts
> +      for (let i = 0; i < length; i++) {
Yeah, I see how it's tricky.

For the first problem, maybe you could pull this out into its own function and pass in the `transactionPlacement` value to use (`ReplacesExecutableTransaction` or `ReplacesFutureTransaction`)

and then also create a function whose sole purpose is to loop of the queue and then execute functions that you give it.

```
function loopTxs(txsToLoop: Transactions[], length: number, fnsToCall: (tx: transaction, nonce: bigint) => boolean[]) {
   for (let i = 0; i < length; i++) {
      const currentTx = txsToLoop[i];
      const thisNonce = currentTx.nonce.toBigInt();
      for (let j = 0, l = fnsToCall.length; j < l; j++) {
        // if a function returns false we can exit early without continuing to loop
        if ( !fnsToCall[j](currentTx, thisNonce) ) return;
      }
   }
}
```

For the `executableOriginTransactions` you'd pass it two functions, the one that does the replacement, and one that keeps track of the `highestNonce`, and for the `queuedOriginTransactions` you'd only pass it the replacement function.

The above example allows for returning `false` from any of the `fnsToCall` in order to stop the loop. This would be only be beneficial in the case of the `queuedOriginTransactions` in the case that it replaces a transaction in the queue, since once that happens we don't need to keep looping. I can explain this idea further over zoom if you'd like, as there is some additional finagling that you'd need to do.

2021-09-24 16:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/transaction-pool.ts
> +            transactionPlacement = TriageOptions.ReplacesFutureTransaction;
we should exit the loop early (`break;`) if we found a replacement, since we aren't ever going to find another.

2021-09-24 16:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/transaction-pool.ts
> +    } else if (transactionPlacement === TriageOptions.Executable) {
Let's reorder this so the most likely case, `TriageOptions.Executable`, is checked first. Also, what do you think about changing these ifs and elses to a `switch`?

2021-09-24 16:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/tests/api/evm/snapshot.test.ts
> +            { from, to, value: value++, nonce: accountNonce + 4 }
Nice find!

2021-09-24 16:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/transaction-pool.ts
> +export enum TriageOptions {
I think this should be `TriageOption`.


It  seems to make more sense when you look at it as a type that holds a singular value:

```
function fn(triageOption: TriageOption) {}
```

2021-09-24 16:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/transaction-pool.ts
> +  ReplacesFutureTransaction = 3
These are excellent descriptions!

2021-09-28 20:22 UTC, davidmurdoch commented
Looks like tests aren't completing right now. See the `removes transactions that are in pending transactions at the start of evm_revert` test. It passes, but then mocha just quits. This seems to happen when Node.js has determined that the application has hit a dead end and thus no more events will be occurring. Let me know if you want to sync on this one!

2021-09-30 15:57 UTC, davidmurdoch approved these changes

2021-09-30 15:57 UTC, merged