use new @trufflesuite/bigint-buffer
ConsenSys-archive/ganache pull request #1414
Opened 2021-10-19 19:48 UTC by MicaiahReid

Previously the bigint-buffer library used by Ganache would fail to build on Windows unless `windows-build-tools` was installed. This would cause the (slower) JS fallback to be used and would display an ugly warning in the console on startup of Ganache. This PR's main objective is to use trufflesuite's new [bigint-buffer](https://github.com/trufflesuite/bigint-buffer) library, which prebuilds all binaries during CI to prevent this warning.

Additionally, this PR:
- removes unnecessary CI installations when Github runs the PR action
- Adds very basic test to check if fallback for bigint-buffer is used.
  - Note: the original bigint-buffer library does NOT fail to build and use the JS fallback in our CI tests. This is because the windows version used by Github actions has the necessary dependencies (python) installed by default. So while the test should accurately tell us if the fallback is used, it shouldn't ever happen in CI so it's not particularly useful.

Closes #1080

2021-11-01 21:41 UTC, davidmurdoch requested changes

2021-11-01 21:41 UTC, davidmurdoch commented on .github/workflows/pr.yml
> +        os: [windows-latest, ubuntu-18.04, ubuntu-20.04, macos-11.0]
Why the change to `windows-latest`? Using the `latest` build makes for potentionally unreproducable CI runs, as github can change what it targets at anytime.

2021-11-01 21:41 UTC, davidmurdoch commented on src/packages/utils/tests/utils.test.ts
> +describe.only("@ganache/utils", () => {
```suggestion
describe("@ganache/utils", () => {
```

2021-11-01 23:42 UTC, MicaiahReid commented on .github/workflows/pr.yml
> +        os: [windows-latest, ubuntu-18.04, ubuntu-20.04, macos-11.0]
```suggestion
        os: [windows-2019, ubuntu-18.04, ubuntu-20.04, macos-11.0]
```

2021-11-03 01:48 UTC, davidmurdoch approved these changes

2021-11-03 17:32 UTC, merged