feat: Add evm_setAccountBalance
ConsenSys-archive/ganache pull request #2337
Opened 2022-02-10 10:49 UTC by rmeissner

Implements #1889

2022-02-10 12:16 UTC, rmeissner commented
@davidmurdoch I was wondering how the api documentation is generated and if there is a need to manually adjust it (e.g. https://github.com/trufflesuite/ganache/blob/develop/docs/typedoc/api.json)

Also I would also try to add logic to set the storage and to set the code for an account. Should this happen in different PRs?

2022-02-10 16:09 UTC, davidmurdoch commented
Wow, at first glance this looks very thorough!

The docs are auto-generated as part of the release and end up [here](https://trufflesuite.github.io/ganache/) (for now). Note that these docs are actually just a proof of concept and will likely be rewritten.

2022-02-10 16:33 UTC, rmeissner commented
Cool :)

Let me know if I should adjust any of the method names (or anything else). 

I am not sure why some of the tests are failing :/

Also another thing I realized is that `src/packages/ganache/npm-shrinkwrap.json` and `src/chains/filecoin/filecoin/package-lock.json` have changes (I assume from running `npm i`). Not sure if this is ok, else I would revert them.

2022-02-14 11:23 UTC, rmeissner commented
@davidmurdoch is there any way to push this forward from my side? I want to use Ganache v7 to simulate Safe transactions and for this I require this functionality :D

2022-02-15 15:20 UTC, MicaiahReid commented
@rmeissner I'll review this today and we can hopefully get it merged this week!

2022-02-15 17:28 UTC, davidmurdoch requested changes
Looks great! Can you drop the filecoin package-lock.json changes? Once that is done this should be good to go on my end!

Excellent work!

2022-02-15 17:29 UTC, davidmurdoch commented
Oh, we have a flaky test and a couple of tests that like like to timeout, so don't worry about the tests failures here.

2022-02-15 18:08 UTC, MicaiahReid requested changes
Great work and thanks for the PR! I've requested a few simple changes.

One thing we (@rmeissner, @davidmurdoch, whoever is interested) should probably discuss is data validation for these methods. Currently, if you send bad data for the balance/code/storage, for example `"0xw"`, it will always respond `true`. Also, if there is some valid data, it will update the balance/code/storage _up to_ the bad data. For example, setting balance to `"0xab;lkjf"` will set the balance to `0xab`. This is also true for `evm_setAccountNonce`, not just these new methods.

2022-02-15 18:08 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/RPC-METHODS.md
> +Sets the given account's balance to the specified value. Mines a new block before returning.
```suggestion
Sets the given account's balance to the specified WEI value. Mines a new block before returning.
```

2022-02-15 18:08 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/RPC-METHODS.md
> +- `balance: QUANTITY` : The balance value to be set.
```suggestion
- `balance: QUANTITY` : The balance value, in WEI, to be set.
```

2022-02-15 18:08 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/api.ts
> +   * Sets the given account's balance to the specified value. Mines a new block
```suggestion
   * Sets the given account's balance to the specified WEI value. Mines a new block
```

2022-02-15 18:08 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/api.ts
> +   * @param balance - The balance value to be set.
```suggestion
   * @param balance - The balance value, in WEI, to be set.
```

2022-02-15 18:11 UTC, rmeissner commented
Yeah, I followed `evm_setAccountNonce`, but I agree some data validation would be nice. Maybe something for a separate PR, but I could look into this.

2022-02-15 18:29 UTC, MicaiahReid approved these changes

2022-02-18 21:04 UTC, merged

2022-02-23 16:52 UTC, davidcallanan commented
Hello, any idea when this is being officially released?