fix: enforce eip-2
ConsenSys-archive/ganache pull request #2944
Opened 2022-04-20 22:54 UTC by davidmurdoch

depends on https://github.com/trufflesuite/ganache/pull/2602, fixes #2600

2022-04-21 16:01 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/wallet.ts
> +          // note: if keccak can return it's own input as it's output, then this
```suggestion
          // note: if keccak can return its own input as its output, then this
```

2022-05-02 14:03 UTC, MicaiahReid requested changes

2022-05-02 14:03 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/wallet.ts
> +const TWELVE_255s = Buffer.allocUnsafe(12).fill(255);
This is a great variable name. Bravo.

2022-05-02 14:03 UTC, MicaiahReid commented on src/chains/ethereum/transaction/tests/index.test.ts
> +            // a common at the genesis (eke chainstart) so we can test at a fork
```suggestion
            // a common at the genesis (aka chainstart) so we can test at a fork
```
Unless `eke` means something I'm not aware of?

2022-05-02 14:03 UTC, MicaiahReid commented on src/chains/ethereum/transaction/tests/index.test.ts
> +      describe("EIP-2", () => {
Cool test!

2022-05-02 14:04 UTC, MicaiahReid commented
Reviewed! This also needs a description that is release ready.

2022-05-02 16:16 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/wallet.ts
> +const TWELVE_255s = Buffer.allocUnsafe(12).fill(255);
Thanks for noticing. This line took me two weeks to get right!

2022-05-02 19:09 UTC, MicaiahReid approved these changes

2022-05-03 00:33 UTC, merged