fix: make forking work in the browser
ConsenSys-archive/ganache pull request #3130
Opened 2022-05-25 15:10 UTC by davidmurdoch

Ganache's zero-config forking feature now works in the browser!

2022-05-26 15:42 UTC, tenthirtyone commented on src/packages/ganache/package.json
> +  "version": "7.1.0-clairvoyance.4",
Sneaky!

2022-06-07 21:59 UTC, davidmurdoch commented
You can test this by checking out this branch and then running:

```console 
$ npm run reinstall && INFURA_KEY=<YOUR INFURA KEY  HERE> npm run build && npm run docs.build && npm run docs.preview
```

then paste the following in any of the editors:

```javascript
const p = ganache.provider({fork:"mainnet"});
console.log(await p.request({method:"debug_traceTransaction", params:["0x560900937892cd888a685c836f666804e05e04f3d161e1751ffb5ab7809c55d9"]}));
```

then wait a while for the result to appear (it can takes a lot of time).

Additionally, you should test the http handler code (the above tests WebSockets):

```javascript
const p = ganache.provider({fork:{url: "<your infura url goes here>"}});
console.log(await p.request({method:"debug_traceTransaction", params:["0x560900937892cd888a685c836f666804e05e04f3d161e1751ffb5ab7809c55d9"]}));
```


Example:

![image](https://user-images.githubusercontent.com/187813/172489954-9ac6e5e5-fcb3-4be4-825b-6ec720534fc6.png)

2022-06-07 23:02 UTC, jeffsmale90 requested changes

2022-06-07 23:02 UTC, jeffsmale90 commented on index.html
> +<!DOCTYPE html>
Should this file be deleted?

2022-06-07 23:02 UTC, jeffsmale90 commented on src/chains/ethereum/ethereum/src/forking/handlers/http-handler.ts
> +        // in the browser we can't detect if the response is compressed (gzip),
Does this imply that we cannot trust the `content-length` in the browser (because it may have been compressed), so we _must_ handle as a chunked response?

2022-06-07 23:41 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +      blockNumber: nextBlock.header.number.toArrayLike(Buffer)
We already polyfill Buffer in the browser, but BN doesn't handle it well, so we have to do it this way .

2022-06-08 12:21 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/forking/handlers/http-handler.ts
> +        // in the browser we can't detect if the response is compressed (gzip),
Right, but I'd word it slightly differently: we can't trust it to mean the length of the decompressed content, as originally implemented.

I will have a follow up PR that adds compression handling to the Node side which handles the Content-Length + Content-Encoding: gzip case by falling back to the chunked handler. It just still needs tests :-)

2022-06-16 18:08 UTC, jeffsmale90 approved these changes
🚢 it!

2022-06-21 16:36 UTC, MicaiahReid requested changes, later dismissed
Soooo cooooooool! All it needs is a release-ready PR description!

I've also pushed two changes to the README to this branch if you could review them. Let me know and I can remove this commits from your branch, I just knew you were out of town and thought it would be easier to push than have you go in and update the README.

2022-06-23 18:25 UTC, davidmurdoch commented
blocked by https://github.com/trufflesuite/ganache/pull/3275

2022-06-24 14:35 UTC, MicaiahReid approved these changes

2022-06-24 15:32 UTC, merged