Handle 'estimate' for defaultTransactionGasLimit on the CLI
ConsenSys-archive/ganache pull request #3233
Opened 2022-06-14 14:06 UTC by tenthirtyone

Previously, `estimate` was causing an error when the miner options would attempt to cast the string to BigInt.

This change adds the `estimateOrToBigIntOrString` function to Ethereum's miner options to intercept and handle the `estimate` option on the cli. 

Related:
https://github.com/trufflesuite/ganache/issues/2398

2022-06-17 20:32 UTC, MicaiahReid requested changes
Tested, looks good! In the description, could you updated it to say "Fixes: #2398" rather than "Related"? This will trigger GitHub to close the issue once merged.

2022-06-22 14:03 UTC, tenthirtyone commented
@MicaiahReid :+1:

2022-06-22 14:59 UTC, MicaiahReid approved these changes

2022-06-22 19:44 UTC, davidmurdoch approved these changes

2022-06-24 17:23 UTC, merged