fix: eth_getWork wrong argument (fixes #3348)
ConsenSys-archive/ganache pull request #3349
Opened 2022-07-11 08:28 UTC by emilbayes

2022-07-12 22:51 UTC, tenthirtyone approved these changes

2022-07-13 18:31 UTC, tenthirtyone requested changes

2022-07-13 18:31 UTC, tenthirtyone commented on src/chains/ethereum/ethereum/src/api.ts
>    @assertArgLength(1)
I was a bit early to this approval. Please update this line to:

`@assertArgLength(0)`

2022-07-13 23:19 UTC, jeffsmale90 approved these changes
Other than @tenthirtyone 's comment, this looks 👍

2022-07-15 14:57 UTC, emilbayes commented
The comment has been resolved @tenthirtyone

2022-07-16 01:12 UTC, tenthirtyone approved these changes

2022-07-18 20:27 UTC, tenthirtyone commented
Ah, related: https://github.com/trufflesuite/ganache/issues/3283

2022-07-22 20:54 UTC, davidmurdoch approved these changes

2022-07-28 01:23 UTC, merged