fix: remove unnecessary TODO from api, update TODO with issue number
ConsenSys-archive/ganache pull request #3472
Opened 2022-08-03 16:00 UTC by tenthirtyone

Housekeeping going through codebase TODOs.

The endpoints for `eth_estimateGas`, `personal_newAccount`, `personal_unlockAccount`, and `debug_storageRangeAt` have outstanding TODOs calling out their [interactive js-docs example](https://trufflesuite.github.io/ganache/) do not work. 

`eth_estimateGas`, `personal_newAccount`, and `personal_unlockAccount` appear to be working.

![image](https://user-images.githubusercontent.com/6285466/182653383-36dca559-4c1a-40cd-ab40-28d3053b8e27.png)

`debug_storageRangeAt` has an existing issue that's been added to its TODO. The original PR added examples to each RPC endpoint and the unnecessary TODOs are likely a copy/paste mistake.

2022-08-03 20:09 UTC, MicaiahReid requested changes
I think I'd probably consider this a `chore` PR rather than a `fix`, but some might disagree. 

Can the description be updated to be release ready?

2022-08-03 20:09 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/data-managers/blocklog-manager.ts
> +
```suggestion
```

2022-08-03 23:00 UTC, jeffsmale90 approved these changes

2022-08-04 03:19 UTC, tenthirtyone commented on src/chains/ethereum/ethereum/src/data-managers/blocklog-manager.ts
> +
:+1:

2022-08-04 14:28 UTC, MicaiahReid approved these changes

2022-08-04 20:44 UTC, davidmurdoch approved these changes

2022-08-04 20:45 UTC, davidmurdoch commented
I've updated the PR title to reflect the plural changes of the PR. When merging this can make sure sure the commit message reflects this change?

2022-08-15 11:05 UTC, merged