fix: assume unknown tx type is `TransactionType.Legacy`
ConsenSys-archive/ganache pull request #3523
Opened 2022-08-11 00:15 UTC by jaketimothy

Fixes #3489
Fixes #3458

2022-08-11 00:15 UTC, jaketimothy commented
Let me know if this is too permissive

2022-08-11 13:01 UTC, MicaiahReid approved these changes
I think I'm cool with this. Thanks for the PR!

I would like to note - this should fix your problems with Arbitrum Nitro throwing with an "invalid transaction types" error, but we still won't actually support these transaction types. Or any non EVM compatible chains. (I know, Arbitrum claims to be EVM compatible, then they go and start making up transaction types! :sweat_smile: )

We are working on a plugin system so that users can extend Ganache to work with different L2s. Keep an eye on our releases for when this will be available. Thanks again!

2022-08-11 17:42 UTC, davidmurdoch requested changes
Awesome! Thanks for doing the work for this. I just have one change request.

2022-08-11 17:42 UTC, davidmurdoch commented on src/chains/ethereum/transaction/tests/index.test.ts
> +        assert.strictEqual(txFromRpc.type.toString(), "0x0");
Can you also add a test to handle the case where the unknown `type` is `"0xc0"` and one more where it some value greater than `"0xc0"`?

2022-08-11 22:02 UTC, davidmurdoch commented
Thanks @jaketimothy for those quick test updates. Tests are running now and we'll get this approved and merged soon!

2022-08-17 05:34 UTC, jaketimothy commented
@davidmurdoch lmk if there's anything more I can take care of here!

2022-08-17 14:42 UTC, davidmurdoch approved these changes
Looks perfect! Thanks!

2022-08-17 14:43 UTC, merged