chore: add sepolia as a hardfork option
ConsenSys-archive/ganache pull request #3580
Opened 2022-08-25 21:40 UTC by tenthirtyone

No code changes here. Just adding sepolia as a hardfork option.

2022-08-26 14:12 UTC, davidmurdoch approved these changes
LGTM! My only suggestion is to change the PR title to start with `feat: `.

2022-08-26 15:07 UTC, MicaiahReid approved these changes

2022-09-04 21:16 UTC, jeffsmale90 requested changes
Just a missing comma

2022-09-04 21:16 UTC, jeffsmale90 commented on src/packages/ganache/README.md
> +                                        [choices: "mainnet", "ropsten", "kovan", "rinkeby", "goerli", "görli"
```suggestion
                                        [choices: "mainnet", "ropsten", "kovan", "rinkeby", "goerli", "görli",
```

2022-09-07 00:54 UTC, jeffsmale90 approved these changes

2022-09-07 01:13 UTC, merged