refactor!: Remove support for kovan test network
ConsenSys-archive/ganache pull request #3732
Opened 2022-09-28 07:31 UTC by jeffsmale90

Removes native support for Kovan test network, as [this network is deprecated](https://ethereum.org/en/developers/docs/networks/#kovan).

Fixes #3706

2022-09-28 09:04 UTC, jeffsmale90 commented
I was unsure about the conventional commit, but after reading a little (including this SO https://stackoverflow.com/questions/48075169/semantic-commit-type-when-remove-something), I figured `refactor!` was probs the best.

Happy to hear alternatives however.

2022-09-28 14:58 UTC, davidmurdoch commented
The "!" indicates a breaking change. Which this change is _not_ because the feature being removed is not being removed by us.

2022-09-28 15:47 UTC, MicaiahReid approved these changes
Looks good. I agree with David on removing the `!` from the title.

2022-09-28 15:49 UTC, MicaiahReid requested changes

2022-09-28 15:49 UTC, MicaiahReid commented on src/packages/ganache/README.md
> +                                        [choices: "mainnet", "ropsten", "rinkeby", "goerli", "görli", "sepolia"]
I think this line is one character longer than it's supposed to be. Can you go back to indenting it?

2022-09-28 15:50 UTC, davidmurdoch commented
And I agree with Micaiah on agreeing with myself on removing the ! from the title.

2022-09-28 15:51 UTC, davidmurdoch requested changes
What Micaiah said. :-)

2022-09-29 07:08 UTC, tenthirtyone approved these changes
Approving, be a rebel and slam the green button

![image](https://user-images.githubusercontent.com/6285466/192963121-833f4650-9ac3-4736-9729-c5b50af9c968.png)

But seriously, conditional on the README change. How does 'ole laser eyes @MicaiahReid spot these?

2022-09-29 07:26 UTC, jeffsmale90 commented
> Approving, be a rebel and slam the green button

At least someone appreciates my work :P

I've fixed the indentation, and removed the ! in the title.

2022-09-29 15:31 UTC, davidmurdoch approved these changes

2022-10-03 13:30 UTC, merged