docs: document `eth_feeHistory` in `RCP-METHODS.md`
ConsenSys-archive/ganache pull request #3840
Opened 2022-10-25 20:16 UTC by davidmurdoch

It does what it says on the label.

2022-10-26 17:08 UTC, tenthirtyone approved these changes

2022-10-27 00:37 UTC, MicaiahReid requested changes

2022-10-27 00:37 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/RPC-METHODS.md
> +- `gasUsedRatio`: - An array of block gas used ratios. These are calculated as the ratio of gasUsed and gasLimit.
```suggestion
- `gasUsedRatio`: - An array of block gas used ratios. These are calculated as the ratio of `gasUsed` and `gasLimit`.
```

2022-10-27 19:22 UTC, MicaiahReid approved these changes

2022-10-27 19:30 UTC, merged