chore: add pr template
ConsenSys-archive/ganache pull request #3970
Opened 2022-11-30 16:27 UTC by MicaiahReid

## PR description

This PR introduces a PR template that will be used to guide contributors on a format for creating PRs in the Ganache repo.

We can bike shed this to our heart's content, but I figured I'd get something out to start the conversation. By the way, this PR description uses the template. 

## Testing instructions

N/A

## Documentation

- [ ] I've added the `doc-change-required` label to this PR so that documentation can be added by the docs team in another PR.
- [ ] I've included documentation changes in this PR:
  - [ ] I've updated the `README.md`.
  - [ ] I've updated the `CONTRIBUTING.md`.
  - [ ] I've added/updated an RPC method in `src/chains/ethereum/ethereum/RPC-METHODS.md`.
  - [ ] I've added/updated a JS-DOC example of a new RPC method in `src/chains/ethereum/ethereum/src/api.ts`.
- [X] This PR does not require documentation changes.
- [ ] I don't know what this PR needs in regards to documentation. 

## Release Notes

This change introduces a PR template that will be used to guide contributors on a format for creating PRs in the Ganache repo.

2022-11-30 21:02 UTC, jeffsmale90 requested changes
I love it!

2022-11-30 21:02 UTC, jeffsmale90 commented on .github/pull_request_template.md
> +<!-- Consider the documentation needs of this PR, and select the appropriate option. -->
Maybe make this _not_ a comment, as it's not immediately clear that only one of these is required.

I always find these sort of "optional" checkboxes to be confusing...

2022-11-30 21:04 UTC, jeffsmale90 commented on .github/pull_request_template.md
> +  - [ ] I've added/updated an RPC method in `src/chains/ethereum/ethereum/RPC-METHODS.md`.
TIL - this doesn't have `eth_getProof`!

2022-11-30 21:05 UTC, jeffsmale90 commented on .github/pull_request_template.md
> +  - [ ] I've added/updated an RPC method in `src/chains/ethereum/ethereum/RPC-METHODS.md`.
https://github.com/trufflesuite/ganache/issues/3972

2022-11-30 21:46 UTC, tenthirtyone approved these changes
:+1: 

I usually see two different types of PR template. This kind and a 'preflgiht pr checklist' is how I think of the 2nd.

https://github.com/devspace/awesome-github-templates

I like these a lot for starting a funnel before we triage issues, too, if it works out for PRs.

2022-12-02 14:50 UTC, MicaiahReid commented
I've rearranged a bit and added some further comments to make very clear that most of the information is optional for external contributors. @davidmurdoch's concern is that these templates will be a barrier to entry or an annoyance for some contributors, and we definitely don't want that. Input welcome.

2022-12-08 09:48 UTC, tenthirtyone approved these changes

2022-12-15 16:11 UTC, davidmurdoch commented
I don't like it :-/

2023-01-10 21:42 UTC, MicaiahReid commented
Seems like this isn't something we think is best for us right now.

2023-01-10 21:42 UTC, closed without merging