chore: remove `Promise.allSettled` shim
ConsenSys-archive/ganache pull request #4003
Opened 2022-12-08 10:02 UTC by tenthirtyone

This was TODO'd to be removed if we bumped `typescript` to `4.2.3+`

2022-12-08 14:23 UTC, MicaiahReid approved these changes
Looks good to me! I don't think you needed to push the shrinkwrap for this one since no dependencies changed. I don't think it will hurt anything, though.

2022-12-08 19:32 UTC, davidmurdoch commented on src/packages/core/src/server.ts
>  import allSettled from "promise.allsettled";
The `promise.allsettled` package itself should be removed.

2022-12-08 19:33 UTC, davidmurdoch requested changes
The `promise.allsettled` package itself should be removed.

2022-12-09 16:57 UTC, davidmurdoch commented
Looks like it doesn't work in Node v12.0.0. Let's wait on this until after the-merge is in

2022-12-15 17:34 UTC, davidmurdoch commented
@tenthirtyone let's merge this one _after_ the merge is released (which should be later today).

2022-12-19 06:43 UTC, jeffsmale90 reviewed
This all looks good to me. If you merge `develop` it'll kill off the node12 builds 🥳

2022-12-19 16:39 UTC, tenthirtyone commented
> This all looks good to me. If you merge `develop` it'll kill off the node12 builds partying_face

@jeffsmale90 - should have been taken care of in https://github.com/trufflesuite/ganache/pull/4003/commits/6268b367cfdb4b3e86b6a37267d3a86b59c824c0

2022-12-19 16:44 UTC, davidmurdoch approved these changes

2022-12-19 16:52 UTC, merged