docs: expand on troubleshooting node-gyp errors
ConsenSys-archive/ganache pull request #4013
Opened 2022-12-10 01:02 UTC by legobeat

node running as root is a common gotcha.

While there are workarounds that make that work (`npm config set user 0`), it seems better to guide towards dropping privileges.

2022-12-14 16:01 UTC, davidmurdoch requested changes

2022-12-14 16:01 UTC, davidmurdoch commented on CONTRIBUTING.md
> +- If you still get errors, [read here](https://blog.logrocket.com/solving-common-issues-node-gyp/).
I don't think we should link out to a 3rd party blog, as we can't trust that the author of the blog will not use our endorsement to trick users.

2022-12-14 22:09 UTC, legobeat commented on CONTRIBUTING.md
> +- If you still get errors, [read here](https://blog.logrocket.com/solving-common-issues-node-gyp/).
```suggestion
```

2022-12-14 23:18 UTC, davidmurdoch approved these changes

2022-12-15 15:09 UTC, MicaiahReid approved these changes

2022-12-21 19:21 UTC, merged