docs: add console.log to all solidity examples in interactive docs
ConsenSys-archive/ganache pull request #4132
Opened 2023-01-06 20:54 UTC by MicaiahReid

All of our RPC methods are documented with examples in our [interactive documentation](https://trufflesuite.github.io/ganache/). Some of these examples even have a simple Solidity contract that is precompiled and is deployed as you run the example. This change updates those precompiled Solidity contracts to include an import of Ganache's `console.sol` package and calls to `console.log`. When you run an example, go to the Ganache Logs tab and you'll see these Solidity `console.log` calls being logged! This change impacts the following RPC methods:
- `eth_call`
- `eth_getBlockByHash`
- `eth_getBlockTransactionCountByHash`
- `eth_getCode`
- `eth_getFilterChanges`
- `eth_getLogs`
- `eth_getFilterLogs`
- `eth_getProof`
- `eth_getStorageAt`
- `debug_traceTransaction`
- `debug_storageRangeAt`

2023-01-10 23:57 UTC, tenthirtyone approved these changes
Pulled down and tested against 4 at random. Looks good. 

One nit: The new logging increase the logs beyond the height of the window for some examples. On xl screens the page is very very wide and very very thin:

![image](https://user-images.githubusercontent.com/6285466/211686458-821c6c89-82d8-48ec-a161-61f2094fa279.png)

2023-01-31 00:39 UTC, jeffsmale90 requested changes

2023-01-31 00:39 UTC, jeffsmale90 commented on src/chains/ethereum/ethereum/src/api.ts
> +   * //          console.log("Called Simple contract constructor. Setting value to 5.");
```suggestion
   * //          console.log("Called Simple contract constructor. Setting `value` to 5.");
```
I think this is a little clearer (that "value" refers to the variable name)

Same as per other instances. It's not a significant issue though, as clearly the contracts are fairly simple.

2023-01-31 14:26 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/api.ts
> +   * //          console.log("Called Simple contract constructor. Setting value to 5.");
¯\_(ツ)_/¯ works for me

2023-01-31 14:27 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/api.ts
> +   * //          console.log("Called Simple contract constructor. Setting value to 5.");
(I don't have the option to use the suggested change)

2023-01-31 14:29 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +   * //          console.log("Called Simple contract constructor. Setting value to 5.");
Seeing your here made my heart hurt.

2023-03-01 19:36 UTC, merged