debug_storageRangeAt implementation
ConsenSys-archive/ganache pull request #755
Opened 2021-01-26 08:47 UTC by eshaben

Resolves #682

2021-01-26 08:50 UTC, eshaben commented
Need to clean up the code (copy pasta from `debug_traceTransaction`), clean up/add typings, add annotations for documentation in api, and probably more... but the logic is there, this is close.

2021-02-09 04:00 UTC, eshaben commented
Hahaha... what my last comment said but hopefully for real this time

2021-02-11 09:07 UTC, eshaben commented
Not the prettiest way of implementing this rpc method but it gets the job done 🤷 

Basically we are storing the raw, un-hashed version of storage keys along with their hashed keys so we can return both hashed and raw keys to the user for the `debug_storageRangeAt` method. Then after we replay the transaction, we use the trie to create a read stream and get all of our storage entries from the transaction. Then we sort the keys before we can filter through the ones we need and return the desired range of storage data.

Findings: geth stores their hashed keys along with the raw, un-hashed keys. geth also sorts their keys after getting them out of the database (see here: https://gist.github.com/eshaben/ae99036dc15a3784ed3ea50856cd733d) 🤷 

This is ready for initial review!

If anyone wants to test against geth, I used the following command to start up a geth console: `geth --rpc --rpccorsdomain="https://remix.ethereum.org" --rpcapi web3,eth,debug,personal,net --vmdebug --datadir test-chain-dir --dev console`
☝️ this command requires you create a directory called `test-chain-dir` for storing chaindata. 

Then I went to remix and deployed my contracts and sent transactions. After sending transactions I went back to geth console and tried to use `debug_storageRangeAt` method, like so...
```
debug.storageRangeAt(
"0x29a4daa5e2a33843a5967e7f6014f95862772fa6077afeddeebc9b85e966dbda", // blockHash
 0, // txIndex
"0xe33983B0ab2E5987e6b88E0a860E859061F08C68", // contractAddress
"0x405787fa12a823e0f2b7631cc41b3ba8828b3321ca811111fa75cd3aa3bb5ace", // startKey
 2 // maxResults
);
```

If you have any questions or want help configuring test environment for this, let me know!

2021-02-19 21:00 UTC, davidmurdoch requested changes
Looking good and loving the new tests! Made some comments and suggestions. I'll do another review once you've done the clean up you mentioned.

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +   * retuns a next key which is the keccak-256 hash of the next key in storage for continuous downloading.
```suggestion
   * returns a next key which is the keccak-256 hash of the next key in storage for continuous downloading.
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +      // save storage keys to the database one at a time
```suggestion
      // save storage keys to the database
```

Because this loop happens within the `batch` callback, teeeecchhhhnically they'll all get saved at the same time :-)

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +   *  5. Filter, assemble, and send storage data for the given range back
:heart:

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +    }
`traceTransaction` shouldn't (:sweat_smile:) have any side effects, so this bit can probably be removed.

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +   * @param maxResult
Can you add descriptions for each of these parameters?

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/miner/miner.ts
> +        };
Let's just modify `runtimeBlock.finalize` to take in `storageKeys` as a param, and then have it output `{block: Block, serialized: Buffer, storageKeys: Map<Buffer, Buffer>}`.

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/miner/miner.ts
> +          storageKeys.set(hashedKey, key.toBuffer());
Because Map's keys don't compare Buffer data, but instead they compare the Buffer _instance_, you could end up with multiple keys that represent the same data. The key probably needs to be converted to a string here.

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/miner/miner.ts
> +          const key = stack[stack.length - 1];
It looks like we only every need the last item from the stack. If `event.stack` is an actually just an array we can skip the `for` loop and do `const key = event.stack[event.stack.length - 1].toArrayLike(Buffer)`

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +import { keccak } from "@ganache/utils/src/utils/keccak";
VS Code like to automatically write these imports, but webpack seems to choke on them. To make it work add `keccak` to the destructuring of `utils` on line 37, i.e., 

```
const {
  BUFFER_EMPTY,
  RPCQUANTITY_EMPTY,
  BUFFER_32_ZERO,
  BUFFER_256_ZERO,
  RPCQUANTITY_ZERO,
  keccak
} = utils;
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +      throw new Error(e);
No need for this try/catch

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts
> +          await provider.send("debug_storageRangeAt", [
Use `assert.rejects` instead of try/catch here

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts
> +      it("should return correct storage given different transaction indexes", async () => {
Because this test modifies the storage the previous tests rely on can we wrap this test in `evm_snapshot` and `evm_revert`? Or maybe move it to it's own `describe`? While it's fine now, if someone adds a similar test to the ones above right below this one, the results will be different depending on if it is run alone (via `it.only`) or with all others).

If you prefer the `evm_snapshot` way, just make sure the `evm_revert` is called within a `finally` block:

```javascript
const snapshotId = await provider.send("evm_snapshot");

try {
  // ...
} finally {
  await provider.send("evm_revert");
}
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts
> +        ]);
a slightly neater way:

```suggestion
        const [txReceipt1, txReceipt2, txReceipt3] = await Promise.all([
          provider.send("eth_getTransactionReceipt", [tx1]),
          provider.send("eth_getTransactionReceipt", [tx2]),
          provider.send("eth_getTransactionReceipt", [tx3])
        ]);
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +    await getStorageKeys();
Can you move the `let keys: Buffer[] = [];` declaration inside the `getStorageKeys` function and then:

```suggestion
    const keys = await getStorageKeys();
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +          .on("data", async data => {
```suggestion
          .on("data", data => {
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/blockchain.ts
> +          .on("end", async () => {
```suggestion
          .on("end", () => {
```

2021-02-19 21:00 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/miner/miner.ts
> +      };
Maybe we can move this type from here (and from the `traceTransaction`) to a common place, maybe `@ganache/ethereum-utils` can export this type?

2021-02-26 00:06 UTC, davidmurdoch requested changes
Only one more little quick fix and I think it's good to go! Awesome work @eshaben !

2021-02-26 00:06 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/miner/miner.ts
>  const { BUFFER_EMPTY, BUFFER_256_ZERO } = utils;
```suggestion
const { BUFFER_EMPTY, BUFFER_256_ZERO, keccak } = utils;
```

2021-02-26 02:17 UTC, merged