fix: make random seed actually random
ConsenSys-archive/ganache pull request #816
Opened 2021-02-26 22:40 UTC by davidmurdoch

The `alea` RNG requires a starting seed (seedrandom doesn't)

2021-03-04 00:11 UTC, seesemichaelj requested changes

2021-03-04 00:11 UTC, mikeseese commented on src/chains/ethereum/options/src/wallet-options.ts
> +        : randomAlphaNumericString(10, new Alea(unseededRng)),
I don't believe this is correct.

Here shows the prng of calling `(new Seedrandom())()`:

![image](https://user-images.githubusercontent.com/549323/109889444-40150980-7c3a-11eb-9eaa-793d45f80a77.png)

But using the code you provided I get a predictable prng from alea:

![image](https://user-images.githubusercontent.com/549323/109889516-5f139b80-7c3a-11eb-9d2c-fa7d1178665d.png)

Perhaps this should be:

```suggestion
        : randomAlphaNumericString(10, unseededRng),
```

I don't see a need to use Alea here, otherwise it would need to be `new Alea(unseededRng())`

2021-03-04 16:15 UTC, davidmurdoch commented on src/chains/ethereum/options/src/wallet-options.ts
> +        : randomAlphaNumericString(10, new Alea(unseededRng)),
Ah, I good catch. I think I just missed _calling_ the seedrandom instance.

2021-03-09 23:41 UTC, seesemichaelj commented on src/chains/ethereum/ethereum/package.json
> -    "@types/seedrandom": "2.4.28",
BTW, seems like this was fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51609

and IIRC how DefinitelyTypesd works, should be upgraded to `@types/seedrandom@3.0.0`

2021-03-09 23:45 UTC, seesemichaelj commented on src/chains/ethereum/options/src/wallet-options.ts
> +const unseededRng = new Seedrandom();
Per the [documentation](https://www.npmjs.com/package/seedrandom#cjs--nodejs-usage), I believe this should be (it fails with the proper types)

```suggestion
const unseededRng = Seedrandom();
```

2021-03-16 15:31 UTC, davidmurdoch commented on src/chains/ethereum/options/src/wallet-options.ts
> +        : randomAlphaNumericString(10, new Alea(unseededRng)),
```suggestion
        : randomAlphaNumericString(10, unseededRng),
```

2021-03-16 15:32 UTC, davidmurdoch commented on src/chains/ethereum/options/src/wallet-options.ts
>        config.deterministic
```suggestion
      config.deterministic === true
```

2021-03-16 15:32 UTC, davidmurdoch commented on src/chains/ethereum/options/src/wallet-options.ts
> +import Seedrandom, { alea as Alea } from "seedrandom";
```suggestion
import Seedrandom from "seedrandom";
```

2021-05-10 23:41 UTC, merged