implement wallet modification/auxiliary
ConsenSys-archive/ganache pull request #841
Opened 2021-03-04 23:26 UTC by seesemichaelj

This PR implements the remaining wallet functions:
- `Filecoin.WalletSetDefault` moves the specified address to the front of the array to become the new default address
- `Filecoin.WalletNew` generates a new account to the wallet
- `Filecoin.WalletList` lists the current addresses in the wallet
- `Filecoin.WalletHas` checks if the wallet has (and therefore can sign for) the specified address
- `Filecoin.WalletDelete` removes the specified address from our wallet; this action is irrevocable sans importing the private key again
- `Filecoin.WalletExport` exports the private key for the specified address if it is in the wallet
- `Filecoin.WalletImport` adds the private key/address to the wallet to be able to sign it
- `Filecoin.WalletSign` signs a buffer with the specified address's private key in the wallet
- `Filecoin.WalletSignMessage` signs a `Message` with the specified address's private key in the wallet
- `Filecoin.WalletVerify` checks if the provided signature is valid for the provided address (doesn't require the address to be in the wallet)
- `Filecoin.WalletValidateAddress` checks if the address is a valid address

2021-03-04 23:32 UTC, tcoulter approved these changes
All good!

2021-03-16 14:58 UTC, davidmurdoch requested changes

2021-03-16 14:58 UTC, davidmurdoch commented on src/chains/filecoin/filecoin/src/things/address.ts
> +    const customBase32Alphabet = "abcdefghijklmnopqrstuvwxyz234567";
I know `customBase32Alphabet` is used in at least 1 other place. Could you make it a constant, or maybe just have a common custom base32.parse function?

2021-03-17 14:17 UTC, davidmurdoch approved these changes

2021-03-17 22:14 UTC, merged