add miner enabling options and methods
ConsenSys-archive/ganache pull request #842
Opened 2021-03-04 23:32 UTC by seesemichaelj

This PR adds the `miner.mine` option to be able to pause/start the miner; see more details from the [comment thread here](https://github.com/trufflesuite/ganache-core/issues/248#issuecomment-780777681). The provided `miner.mine` option is in addition to `miner.blockTime`. The latter dictates how frequently to mine (instantly or on an interval), and `miner.mine` specifies whether or not to actually use `miner.blockTime`.

2021-03-04 23:38 UTC, tcoulter requested changes
Looks good. One to two new tests would be awesome. See comment!

2021-03-04 23:38 UTC, tcoulter commented on src/chains/filecoin/filecoin/tests/api/filecoin/ganache.test.ts
> +      });
Can we add a test that checks the effects of turning the miner off? e.g., when you start up a blockchain while mining on a timer, then disable the miner, can we ensure it doesn't continue to create blocks? Another good thing might be to start up the miner again afterward and ensure it continues mining after being disabled, then reenabled.

2021-03-08 21:09 UTC, tcoulter approved these changes
Nice work Seese!

2021-03-16 14:34 UTC, davidmurdoch approved these changes, later dismissed
Looks good. I should probably mimic your miner start/stop behavior on the Ethereum side!

2021-03-16 20:55 UTC, seesemichaelj commented on src/chains/filecoin/filecoin/src/blockchain.ts
> +      this.miningTimeout = setInterval(
We should use a recursive `setTimeout` implementation; see https://github.com/trufflesuite/ganache-core/pull/836#discussion_r595207331

2021-03-17 02:58 UTC, seesemichaelj commented
alright @davidmurdoch, I added the recursive `setTimeout` stuff in this PR

2021-03-17 14:19 UTC, davidmurdoch approved these changes

2021-03-17 22:14 UTC, merged