implement `Filecoin.ClientGetDealInfo`
ConsenSys-archive/ganache pull request #846
Opened 2021-03-04 23:46 UTC by seesemichaelj

This PR adds the `Filecoin.ClientGetDealInfo` which queries the `DealInfo` object for a `deal.ProposalCid`. This was requested by Rosco for usage within the Truffle integration.

2021-03-04 23:47 UTC, tcoulter requested changes
Potential good test below

2021-03-04 23:47 UTC, tcoulter commented on src/chains/filecoin/filecoin/tests/api/filecoin/deals.test.ts
> +      });
Add a test that checks behavior when you pass a CID we don't know about?

2021-03-04 23:48 UTC, tcoulter commented on src/chains/filecoin/filecoin/tests/api/filecoin/deals.test.ts
> +      });
Might be good to see what Lotus

2021-03-08 21:12 UTC, tcoulter approved these changes
👏

2021-03-16 15:05 UTC, davidmurdoch approved these changes

2021-03-17 22:15 UTC, merged