Enable webpack building for `@ganache/filecoin-options`
ConsenSys-archive/ganache pull request #853
Opened 2021-03-08 20:43 UTC by seesemichaelj

This PR makes the necessary changes to enable webpack bundling for `@ganache/filecoin-options` so Ganache UI doens't need to run the provider to get default options

2021-03-08 21:13 UTC, tcoulter approved these changes
✔️

2021-03-16 15:24 UTC, davidmurdoch requested changes

2021-03-16 15:24 UTC, davidmurdoch commented on src/chains/filecoin/options/package.json
> +    "build": "npx webpack",
i don't think you need `npx` here, since it is installed as a devDependency.

2021-03-17 14:38 UTC, davidmurdoch approved these changes

2021-03-17 22:16 UTC, merged