implement `Filecoin.ClientGetDealStatus` method
ConsenSys-archive/ganache pull request #855
Opened 2021-03-08 20:46 UTC by seesemichaelj

This PR implements the `Filecoin.ClientGetDealStatus` method, requested for usage within Truffle

2021-03-08 21:17 UTC, tcoulter requested changes
See comments!

2021-03-08 21:17 UTC, tcoulter commented on src/chains/filecoin/filecoin/tests/api/filecoin/deals.test.ts
> +          status = await client.clientGetDealStatus(500);
You're missing something here! Talk to Seese, who knows more!

2021-03-08 21:18 UTC, tcoulter approved these changes
Looks good!

2021-03-16 15:25 UTC, davidmurdoch approved these changes

2021-03-17 22:17 UTC, merged