Improve interactive docs
ConsenSys-archive/ganache pull request #878
Opened 2021-03-19 17:43 UTC by eshaben

- [x] Fill out descriptions (source, arguments, returns) for each RPC method
- [x] Add example for each RPC method
- [x] Create mobile first layout with collapsible side nav

This PR addresses a small part of #680

2021-06-08 01:07 UTC, davidmurdoch requested changes

2021-06-08 01:07 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +   * console.log(isLocked);
```suggestion
   * const isUnlocked = await provider.send("personal_unlockAccount", [newAccount, passphrase] );
   * console.log(isUnlocked);
```

2021-06-08 01:07 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +   * private key belogging to `tx.from` the transaction is verified, signed and
```suggestion
   * private key belonging to `tx.from` the transaction is verified, signed and
```

2021-06-08 01:07 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +  // TODO: example doesn't return correct value
Do we know what is wrong here? I think everything is working and this line can be removed.

2021-06-08 01:07 UTC, davidmurdoch commented on src/chains/ethereum/ethereum/src/api.ts
> +   * const signedTx = await provider.request({ method: "personal_signTransaction", params: [{ from, to}, passphrase] });
```suggestion
   * const signedTx = await provider.request({ method: "personal_signTransaction", params: [{ from, to }, passphrase] });
```

2021-06-15 14:28 UTC, MicaiahReid commented on src/chains/ethereum/ethereum/src/api.ts
> +  // TODO: example doesn't return correct value
I was able to take the returned txHash to retrieve a receipt, so I think this is working as expected. Removing line.

2021-08-03 21:38 UTC, davidmurdoch approved these changes

2021-08-04 02:27 UTC, merged